import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "../components/myHeader.jsx";
import Header1 from "../components/Header.jsx";
const inter = Inter({ subsets: ["latin"] });
const logo = require("../images/cake-busd.png");
const logo1 = require("../images/busd-icon.png");
const logo2 = require("../images/level-icon.png");
import ExampleHeader from "@/components/thheader.jsx";
import ExampleModal from "@/components/mymodal.jsx";
import ExampleB from "@/components/abutton.jsx";
import ExampleA from "@/components/bbutton.jsx";
import ExampleFF from "@/components/footer.jsx";
import Example from "@/components/MyChart.jsx";
import ExampleC from "@/components/Chart2.jsx";
import { useContractReads, WagmiConfig, useAccount } from "wagmi";
import { watchBlockNumber } from "@wagmi/core";
import MyDropDown from "@/components/dropdown.jsx";
import { Fragment, useState } from "react";
import { Listbox, Transition } from "@headlessui/react";
import { CheckIcon, ChevronUpDownIcon } from "@heroicons/react/20/solid";
import ZapperDepositModal from "@/components/ZapperModal.jsx";
function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}
const people = [
  { name: "BUSD" },
  { name: "ETH" },
  { name: "WBNB" },
  { name: "ARB" },
  { name: "USDC" },
  { name: "DAI" },
];
const people1 = [
  { name: "BUSD" },
  { name: "ETH" },
  { name: "WBNB" },
  { name: "ARB" },
  { name: "USDC" },
  { name: "DAI" },
];
export default function Zapper() {
  const [selected, setSelected] = useState(people[0]);
  const [selected1, setSelected1] = useState(people1[0]);
  return (
    <>
      <Head>
        <title>Lodge Capital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class="bg-[url('https://cdn.discordapp.com/attachments/943951700379721740/1075814264163541122/lodge-bg.png')] w-screen  min-h-screen  bg-no-repeat bg-cover bg-center ">
        <ExampleHeader />

        <div className="text-white  gap-6 lg:grid grid-cols-2 lg:grid-cols-12 grid-rows-1 lg:grid-rows-6 lg:gap-1">
          <div className="flex-auto font-lodge text-5xl col-start-5 col-span-4 row-start-2 text-center ">
            BONDS
          </div>
          <div className="flex-auto  font-lodge text-xl col-start-6 col-span-2 row-start-3 text-center "></div>

          <div className=" rounded-xl text-black   flex-auto m-10 md:mx-60 lg:m-10 sm:mx-52 text-xl 2xl:col-start-3 2xl:col-span-3 lg:col-span-3 lg:col-start-3 row-start-3 row-span-3  text-center  bg-white  ">
            <div className="mt-2 font-semibold">PURCHASE</div>
            <div className="text-lg m-2">
              <div class=" inline-flex  text-center justify-center items-center justify-self-center">
                <img
                  class="text-center h-24 bg-white rounded-full"
                  src={
                    "https://media.tenor.com/9SQD7cT_c2sAAAAd/lodgecapital.gif"
                  }
                />
              </div>
              <div className="">
                <button className="text-xl text-center justify-self-center flex-auto mt-4    rounded-lg p-0.5 px-20 sm:px-2 bg-black hover:scale-110 text-white border-2 border-white  hover:bg-white hover:text-black hover:border-2 hover:border-black  transition duration-300 ease-in-out">
                  Purchase
                </button>
              </div>
            </div>
            <div className="flex-auto m-2"></div>
          </div>
          <div className="rounded-xl text-black  flex-auto   m-10 md:mx-60 lg:m-10 sm:mx-52 text-xl 2xl:col-start-8 2xl:col-span-3 lg:col-start-8 lg:col-span-3 row-start-3 row-span-3  text-center bg-white    ">
            <div className="mt-2 font-semibold">REDEEM</div>
            <div className="m-2">
              <div class=" inline-flex  text-center justify-center items-center justify-self-center">
                <img
                  class="text-center h-24 bg-white rounded-full"
                  src={"https://media.tenor.com/1NNu4kkLgxoAAAAC/lodge.gif"}
                />
              </div>
              <div className="">
                <button className="text-xl text-center justify-self-center flex-auto mt-4    rounded-lg p-0.5 px-20 sm:px-2 bg-black hover:scale-110 text-white border-2 border-white  hover:bg-white hover:text-black hover:border-2 hover:border-black  transition duration-300 ease-in-out">
                  Redeem
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="text-lg   text-center text-white ">
          Purchasing SQUARE contributes to bringing LEVEL back to peg by burning
          the amount being sold. You can purchase SQUARE when Current TWAP Peg
          is below 1.00.
        </div>

        <ExampleFF className="sticky top-[100vh]" />
      </main>
    </>
  );
}
