import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "../components/myHeader.jsx";
import Header1 from "../components/Header.jsx";
const inter = Inter({ subsets: ["latin"] });
const logo = require("./lodge-crest-1.png");
import ExampleP from "@/components/pricing.jsx";
import ExampleHeader from "@/components/thheader.jsx";
import ExampleFF from "@/components/footer.jsx";
import ExampleCAR from "@/components/errorallert.jsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Lodge Capital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black h-full">
        <ExampleHeader />
        <ExampleCAR />
        <ExampleP className="" />
        <ExampleFF />
      </main>
    </>
  );
}
