import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "../components/myHeader.jsx";
import Header1 from "../components/Header.jsx";
const inter = Inter({ subsets: ["latin"] });
const logo = require("./lodge-crest-1.png");
import ExampleP from "@/components/pricing.jsx";
import ExampleHeader from "@/components/thheader.jsx";
import Modal1 from "@/components/Wmodal.jsx";
import { CheckIcon } from "@heroicons/react/20/solid";
import ExampleFF from "@/components/footer.jsx";
import ExampleCA from "@/components/contestAlert.jsx";
import WildCardModal from "@/components/Wmodal.jsx";
import ExampleCAR from "@/components/errorallert.jsx";

export default function Home() {
  function classNames(...classes) {
    return classes.filter(Boolean).join(" ");
  }
  return (
    <>
      <Head>
        <title>Lodge Capital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class="bg-black h-full">
        <ExampleHeader />

        <ExampleCA />
        <div className="bg-black py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-4xl text-center grid grid-cols-12 grid-rows-6">
              <p className="md:-mt-40 text-4xl   text-gray-300 sm:text-5xl col-start-5 row-start-3 z-50  font-lodge  absolute justify-center items-center self-center object-center origin-center place-self-center">
                WildCards
              </p>{" "}
              <img
                src="https://cdn.discordapp.com/attachments/943951700379721740/1072918860514197514/tarot-cards.webp"
                className=" col-start-3 row-span-6 col-span-8 row-start-1 z-10  "
              ></img>
            </div>
            <p className="mx-auto mt-6 max-w-2xl text-center text-lg leading-8 text-gray-300 ">
              Unlike Wildcards EVERY Mystery Box contains a powerful Utility NFT
              that stays with you for life and the 3 Degrees represent the 3
              levels of power contained in each Box ✅
            </p>
            <p className="mx-auto  max-w-2xl text-center text-lg leading-8 text-gray-300">
              50% of all Mystery Box sales are wrapped into liquidity and burned
              🔥
            </p>
            <div className="mt-16 flex justify-center items-center"></div>
            <div className="isolate mx-auto mt-10 grid max-w-md grid-cols-1 gap-8 lg:mx-0 lg:max-w-none lg:grid-cols-3">
              <r
                className={classNames(
                  " ring-8 border-2 border-white ring-white/10 col-start-2",
                  "rounded-3xl p-8 xl:p-10"
                )}
              >
                <div className="flex items-center justify-between gap-x-4">
                  <h3 className="text-lg font-semibold leading-8 text-white">
                    The card
                  </h3>
                </div>
                <p className="mt-4 text-sm leading-6 text-gray-300">
                  bla blaaa
                </p>
                <p className="mt-6 flex items-baseline gap-x-1">
                  <span className="text-4xl font-bold tracking-tight text-white">
                    $33
                  </span>
                  <span className="text-sm font-semibold leading-6 text-gray-300">
                    /Card
                  </span>
                </p>

                <WildCardModal />

                <ul
                  role="list"
                  className="mt-8 space-y-3 text-sm leading-6 text-gray-300 xl:mt-10"
                >
                  <li className="flex gap-x-3">
                    <CheckIcon
                      className="h-6 w-5 flex-none text-white"
                      aria-hidden="true"
                    />
                    One Early Exit From the Masonry (LODGE and LEVEL)
                  </li>
                  <li className="flex gap-x-3">
                    <CheckIcon
                      className="h-6 w-5 flex-none text-white"
                      aria-hidden="true"
                    />
                    10% off buy tax for 30 days
                  </li>
                  <li className="flex gap-x-3">
                    <CheckIcon
                      className="h-6 w-5 flex-none text-white"
                      aria-hidden="true"
                    />
                    ZERO BUY TAXES for 30 days
                  </li>
                  <li className="flex gap-x-3">
                    <CheckIcon
                      className="h-6 w-5 flex-none text-white"
                      aria-hidden="true"
                    />
                    Two Wildcards
                  </li>
                  <li className="flex gap-x-3">
                    <CheckIcon
                      className="h-6 w-5 flex-none text-white"
                      aria-hidden="true"
                    />
                    0.6 DUES in a 30 day lock
                  </li>
                </ul>
              </r>
            </div>
          </div>
        </div>
        <ExampleFF />
      </main>
    </>
  );
}
