import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "../components/myHeader.jsx";
import Header1 from "../components/Header.jsx";
const inter = Inter({ subsets: ["latin"] });
const logo = require("./lodge-crest-1.png");
import ExampleH from "@/components/heroex.jsx";
import ExampleHeader from "@/components/thheader.jsx";
import ExampleFF from "@/components/footer.jsx";
import ExamplePage from "@/components/WRpage.jsx";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class="bg-black  min-h-screen ">
        <ExampleHeader />
        <ExamplePage />
        <ExampleFF className=" sticky top-[100vh]" />
      </main>{" "}
    </>
  );
}
